### ISSUE TITLE
How use ch.elexis.sdk

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#35]
I stumbled over the subproject "ch.elexis.sdk", which looks interesting to simplify the setup of the build environment. But I just  don't get, how I should use oomph installer. It just offers to install some eclipse installations, which I could also easily download elsewhere. How apply your elexis build?

(Yes, there is a lot of Information at http://wiki.eclipse.org/Eclipse_Oomph_Installer. I browsed about half an hour without finding a starter: "How should I use it?" or: "what is it all about?")

Can you give me a link?

**Comment by col-panic** [comment]
I started to create a documentation on how to use it, and yet it stopped working ... https://www.eclipse.org/forums/index.php/m/1695478/#msg_1695478 ... Oomph is powerful and nice to use, but there seems to be some constant effort required to keep it up to date enough to have it actually working ... so its currently broken. Will keep you up to date!

**Comment by col-panic** [comment]
I found out, that I already had a newer file .... stupid me ... and did some documentation updates, please see https://github.com/elexis/elexis-3-core/tree/master/ch.elexis.sdk 

any feedback welcome! :)

**Comment by rgwch** [comment]
First it looks really great: Runs unattended for a long, ling time and does many things. But them, suddenly:
--------------
Fetching org.sonatype.tycho.m2e_0.9.0.201412222151.jar from http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.9.0/N/LATEST/plugins/
Fetching org.sonatype.tycho.m2e.feature_0.9.0.201412222151.jar from http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.9.0/N/LATEST/features/
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:249)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$2.commit(ProfileTransactionImpl.java:488)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:323)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:701)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2901)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2845)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2826)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2757)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:539)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:624)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=_Users_gerry_Documents_oomph_elexis_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,fr.obeo.releng.targetplatform,2.1.1.201410251450
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: org.eclipse.update.feature,fr.obeo.releng.targetplatform-feature,2.1.1.201410251450
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,fr.obeo.releng.targetplatform.ui,2.1.1.201410251450

Took 935 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

-------------------
As usual, maven seems to make trouble. We just don't like each other, maven and I....

**Comment by rgwch** [comment]
I just restarted the process, and that times it goes on until here:

Executing startup tasks
Product org.eclipse.products.epp.package.rcp.mars
Project com.github.user.project.elexis.master
Bundle org.eclipse.oomph.setup 1.1.0.v20150504-1714, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Bundle org.eclipse.oomph.setup.core 1.1.0.v20150513-1309, build=1230, branch=master, commit=982807efa21a5b6218c7e6e46c7b377e24f0834e
Bundle org.eclipse.oomph.setup.git 1.1.0.v20150428-1003, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Bundle org.eclipse.oomph.setup.jdt 1.1.0.v20150428-1003, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Bundle org.eclipse.oomph.setup.mylyn 1.1.0.v20150428-1003, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Bundle org.eclipse.oomph.setup.p2 1.1.0.v20150504-1714, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Bundle org.eclipse.oomph.setup.pde 1.1.0.v20150428-1003, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Bundle org.eclipse.oomph.setup.projects 1.1.0.v20150428-1003, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Bundle org.eclipse.oomph.setup.workingsets 1.1.0.v20150428-1003, build=1193, branch=440e3146acd6e5ad35a0359bd0a295315fb53ab1, commit=440e3146acd6e5ad35a0359bd0a295315fb53ab1
Performing Preference /instance/org.eclipse.ui.ide/WORKSPACE_NAME = Elexis
Performing Git Clone git@github.com:elexis/elexis-3-core.git  (master)
Cloning Git repo git@github.com:elexis/elexis-3-core.git to /Users/gerry/Documents/oomph/elexis/git/elexis-3-core
java.lang.Exception: org.eclipse.jgit.api.errors.TransportException: git@github.com:elexis/elexis-3-core.git: Auth fail
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:718)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2901)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2860)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:3945)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:3939)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:3937)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2851)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2826)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2757)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:539)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:624)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:elexis/elexis-3-core.git: Auth fail
  at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
  at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
  at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.cloneRepository(GitCloneTaskImpl.java:774)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:658)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2901)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2860)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:3945)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:3939)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:3937)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2851)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2826)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2757)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:539)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:624)
  ... 1 more
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:elexis/elexis-3-core.git: Auth fail
  at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
  at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
  at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
  at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
  at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
  at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
  at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
  at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
  at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
  at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.cloneRepository(GitCloneTaskImpl.java:774)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:658)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2901)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2860)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:3945)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:3939)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:3937)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2851)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2826)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2757)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:539)
  ... 2 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
  at com.jcraft.jsch.Session.connect(Session.java:512)
  at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
  at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
  at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
  at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
  at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
  at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
  at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
  at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
  at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
  at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.cloneRepository(GitCloneTaskImpl.java:774)
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:658)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2901)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2860)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:3945)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:3939)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:3937)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2851)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2826)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2757)
  ... 3 more

Took 3 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

**Comment by col-panic** [comment]
It only takes a long time the first time you do it, all artefacts are being locally cached. I just re-tried and it worked for me on the before part. Your problem here is the configuration with github, you should have set your github account here.

TransportException: git@github.com:elexis/elexis-3-core.git: Auth fail

there should be something like rgwch@github.com - oomph caches your credentials.

I'll try to re-enact it!

**Comment by col-panic** [comment]
Maybe this helps out - I ll add it to the docu later on

![oomphconfiguration](https://cloud.githubusercontent.com/assets/1679857/7653282/cfc11d74-fb14-11e4-8919-4154a9784d24.png)

**Comment by rgwch** [comment]
Yay! now it works almost :)
Only "at.medevit.atc_codes.test" wants  java 1.6 as compile environment (while I have both java 1.7 and java 1.8 installed), and of course has compile errors.

Wow, and there are even run configurations ready. Click on Elexis Core (OS X), and ....
*...Reference to undefined variable jrebel_args*

But after removal of this...

WOW! It's alive!!!

java.lang.UnsupportedClassVersionError: ch/elexis/core/ui/medication/views/FixMediDisplay : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoad

Okay, some final polishing still required...

But: Yes, I like it. :) And its far easier than all other setup methods I tried up to now. Thanks for your help.

**Comment by col-panic** [comment]
Thanks for the feedback, i fixed the two points you mentioned! :) The environment is quite powerful, and if one changes requirements, like adding a certain software module required in the IDE it will be installed the next time you start the IDE! So you will not have to care about this! 

If you want to go for medelexis development, simply add the required medelexis bits!

all the best!
