### ISSUE TITLE
Fehler im oomph installer

### ISSUE THREAD

**Issue by danielludin** [elexis/elexis-3-core#42]
ich wollte den oomph installer ausprobieren, und bekam folgenden fehler:

Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:414)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:326)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3028)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2957)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2938)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2829)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:552)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:671)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1453217987150
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Target Platform Definition DSL and Generator 2.1.1.201410251450 (fr.obeo.releng.targetplatform-feature.feature.group 2.1.1.201410251450) requires 'org.eclipse.xtext.runtime.feature.group 2.7.0' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1453217987150
    ERROR: org.eclipse.equinox.p2.director code=0 To: fr.obeo.releng.targetplatform-feature.feature.group 0.0.0

Took 9 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

**Comment by col-panic** [comment]
Interessant, könntest du mal ein plain Mars SR1 runterladen, und 
versuchen das 
https://github.com/mbarbero/fr.obeo.releng.targetplatform/commits/master 
zu installieren - mittels dieser Adresse 
http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/latest/

wenn das nicht funktioniert, dann müssten wir direkt bei dem projekt 
einen bug-report machen!

Daniel Ludin wrote:

**Comment by ngiger** [comment]
Okay. Ich habe es gefunden. Das com.essiembre.eclipse.rbe.feature.group kann nicht installiert werden.

Nachdem ich rausgenommen hatte, konnte ich alles instalieren.

Ich werde mal schauen, ob nur das dazugehörende Repository fehlt oder was genau das Problem ist.

**Comment by ngiger** [comment]
Nachdem ich den Eclipse BundlePoll gelöscht hatte, konnte ich direct ab der URL das Elexis.setup laden und die Installation lief.

@Daniel: Kannst Du das bei Dir nachvollziehen? Und das Problem so lösen?

Details im "Commit":https://github.com/elexis/elexis-3-core/commit/ac7162f5df5b6b80ea5aaa8e1a5d7214b4462962

**Comment by danielludin** [comment]
Lieber Niklaus

ich werde erst morgen dazu kommen, und mache dann eine Mitteilung.
Merci für die Info!

Daniel Ludin

**Comment by danielludin** [comment]
@Niklaus

jetzt erscheint bei “Confirmation” des Installers nur noch ein Bootstrap Task, nämlich der P2 Director. (s. Screenshot)
Entsprechend schlägt es fehl – es wird nur ein leeres eclipse gestartet.
habe es zwei mal probiert.

**Comment by ngiger** [comment]
Hast Du vergessen, den Taks mit dem Gelben Pfeil nach unter zu aktivieren?

**Comment by danielludin** [comment]
ach ja sorry, kenne das ding noch nicht lange.

aber jetzt gibt es den fehler:

Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:414)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:326)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3028)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2957)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2938)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2829)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:552)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:671)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1453470520760
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Target Platform Definition DSL and Generator 2.1.1.201410251450 (fr.obeo.releng.targetplatform-feature.feature.group 2.1.1.201410251450) requires 'org.eclipse.xtext.runtime.feature.group 2.7.0' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1453470520760
    ERROR: org.eclipse.equinox.p2.director code=0 To: fr.obeo.releng.targetplatform-feature.feature.group 0.0.0

**Comment by ngiger** [comment]
Schmeiss nochmals den BundlePool weg und beim Update wähle "Mirror" ab. Eventuell wird bei Dir ein nicht korrekter Mirror gebraucht.

**Comment by danielludin** [comment]
So läuft die Installation jetzt zwar fehlerfrei durch,
aber die Setup Tasks werden nicht ausgeführt –> keine Projekte im Project Explorer.
DL

**Comment by ngiger** [comment]
Hatte heute keine Probleme mit OOMPH
