### ISSUE TITLE
Fehler beim HL7 Import

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#44]
Wenn ein HL7 file den Patienten nicht auflösen kann, wurde früher eine Dialogbox zum Suchen des Kontakts geöffnet.

Jetzt führt es zu folgendem Fehler, wenn der im HL7-File genannte Patient nicht gefunden wird:

!ENTRY ch.elexis.core.ui 4 0 2016-07-01 15:07:34.933
!MESSAGE Fehler beim Import null argument:
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: null argument:
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
    at ch.elexis.core.data.beans.base.BeanPersistentObject.<init>(BeanPersistentObject.java:26)
    at ch.elexis.core.data.beans.ContactBean.<init>(ContactBean.java:35)
    at ch.elexis.core.ui.importer.div.importers.ImporterPatientResolver.resolvePatient(ImporterPatientResolver.java:48)
    at ch.elexis.hl7.HL7Reader.resolvePatient(HL7Reader.java:56)
    at ch.elexis.hl7.v2x.HL7ReaderV24.setPatient(HL7ReaderV24.java:235)
    at ch.elexis.hl7.v2x.HL7ReaderV24.readObservation(HL7ReaderV24.java:75)
    at ch.elexis.core.importer.div.importers.HL7Parser.parse(HL7Parser.java:114)
    at ch.elexis.core.importer.div.importers.HL7Parser.importFile(HL7Parser.java:313)
    at ch.elexis.core.importer.div.importers.HL7Parser.importFile(HL7Parser.java:282)
    at ch.elexis.laborimport.RischBern.Importer.importDirect(Importer.java:166)
    at ch.elexis.laborimport.RischBern.Importer.doImport(Importer.java:203)
    at ch.elexis.core.ui.util.ImporterPage$ImporterJob.run(ImporterPage.java:119)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
15:07:38.210 [Timer-2] DEBUG FileTool - Heartbeat

Danach bricht der Import ab.

**Comment by huthomas** [comment]
Ich konnte den Fehler im master branch nicht reproduzieren. Das kann dort nur auftreten, wenn im Auswahldialog niemand ausgewählt wurde.

**Comment by rgwch** [comment]
Das ist so, ja. Sorry, habe es oben falsch beschrieben: Dass man keinen passenden Patienten findet, ist ein Use-Case, der vorkommt. Der Anwender klickt dann "cancel". Dann sollte der Import dieses HL7-File einfach übergehen und mit dem nächsten weitermachen. (Da das file im Eingangsverzeichnis bleibt, kann man sich später darum kümmern). Ich versuche mal, das Problem zu reproduzieren (mehrere HL7-Files geholt, in einem davon unbekannter Patient, werden alle anderen importiert?) und schreibe dann wieder.

**Comment by rgwch** [comment]
Man kann den Fehler folgendermassen reproduzieren;

- mehrere HL7-Dateien ins import-Verzeichnis. Eines davon mit einem Patienten, der nicht in der Datenbank ist
- Import anstossen

Altes Verhalten: Dialog zur Patientenauswahl Poppt auf, man klickt "Cancel", es kommt eine Meldung, der Patient sei nicht in der Datenbank und der Import geht weiter. Am Ende befinden sich nur noch die zurückgewiesenen HL7-Dateien im Import-Verzeichnis.

Neues Verhalten: Dialog Poppt auf, man klickt "Cancel", es kommt eine Fehlermeldung: "Fehler beim Import: Null Argument". Danach hört der Import auf, und alle weiteren Hl7-Dateien bleiben unbearbeitet im Import-Verzeichnis.

**Comment by rgwch** [comment]
Man kann es auch ganz einfach reproduzieren: Eine Datei mit einem unbekannten Patienten als Datei importieren.
Zum Beispiel diese:
[unknown.hl7.txt](https://github.com/elexis/elexis-3-core/files/355642/unknown.hl7.txt)

Der Import bricht mit einer nichtssagenden Fehlermeldung ab, nachdem man in der Patientenauswahlbox "cancel" geklickt hat.

**Comment by ngiger** [comment]
Dieser Fehler ist in der Zwischenzeit behoben. Ich konnte heute ohne Probleme im 3.1-Prerelease oben erwähnte Datei einlesen und wurde nach Labor und Patient gefragt.
