### ISSUE TITLE
Stuck at login screen after updating to version 3.9

### ISSUE THREAD

**Issue by MakeITBetterSAGL** [elexis/elexis-3-core#511]
Hello folks,
I just installed Elexis 3.9 in a new folder (since updating via p2 was not working).
Everything seems ok and a "database update" has been executed successfully, but when the login screen appears there is no reaction after clicking the authentication button. 
So I tried to set username and password in the elexis.ini file. The login screen doesn't appear anymore, but this is the error I get in the log file.

Thanks for your precious help/support and best regards.  :-)
Remo (for Dr. Isabel Strobel in Chiasso). 

!SESSION 2023-04-21 10:14:01.322 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_CH
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2023-04-21 10:14:18.447
!MESSAGE Application error
!STACK 1
Local Exception Stack:
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.10.v20211216-fe64cd39c3): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: Unknown column 'allow_external' in 'field list'
Error Code: 1054
Call: SELECT ID, is_active, is_administrator, allow_external, DELETED, EXTINFO, HASHED_PASSWORD, KEYSTORE, LASTUPDATE, SALT, TOTP, KONTAKT_ID FROM USER_ WHERE (ID = ?)
    bind => [pediatria]
Query: ReadObjectQuery(name="readUser" referenceClass=User sql="SELECT ID, is_active, is_administrator, allow_external, DELETED, EXTINFO, HASHED_PASSWORD, KEYSTORE, LASTUPDATE, SALT, TOTP, KONTAKT_ID FROM USER_ WHERE (ID = ?)")
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:691)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2105)
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:277)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectOneRow(DatasourceCallQueryMechanism.java:766)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRowFromTable(ExpressionQueryMechanism.java:2839)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRow(ExpressionQueryMechanism.java:2792)
    at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:561)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232)
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191)
    at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:447)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3004)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.executeQuery(EntityManagerImpl.java:1012)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.findInternal(EntityManagerImpl.java:954)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:830)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:720)
    at ch.elexis.core.jpa.model.adapter.AbstractModelService.load(AbstractModelService.java:71)
    at ch.elexis.core.services.IModelService.load(IModelService.java:100)
    at ch.elexis.core.services.IModelService.load(IModelService.java:43)
    at ch.elexis.core.services.internal.EnvVarsLoginContributor.performLogin(EnvVarsLoginContributor.java:41)
    at ch.elexis.core.ui.internal.CoreOperationAdvisor.performLogin(CoreOperationAdvisor.java:166)
    at ch.elexis.core.application.Desk.start(Desk.java:148)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'allow_external' in 'field list'
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1015)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:651)
    ... 40 more

**Comment by MakeITBetterSAGL** [comment]
Hi col-panic,
thanks for answering. :-)
1) I checked the user_ table and there is no allow_external column. I will add it and try. Is this a int type or other kind of type?
1.1) Yes the ignorecase is set
2) Yes downloaded it from the suggested link. 
3) When updating via p2 I was getting an error saying that I could not install 3.7 and 3.9 at the same time even if I disabled the 3.7 repository. 

I will try adding a allow_external user column and will let you know what happens. 
Thanks again. :-)
Remo

**Comment by col-panic** [comment]
I would not recommend updating manually. It seems like you took a direct version jump from 3.7 to 3.9. 
This is **NOT SUPPORTED**. If you want to upgrade from 3.7 to 3.9, you first have to install a 3.8, s.t.
all required database changes are done. Also you should check to have a fullly updated 3.7 before installing
3.8!

Anyways, the formal definition can be found here https://github.com/elexis/elexis-3-core/blob/5353a35926dc9aff1aa35960bb02529658e74cbb/bundles/ch.elexis.core.jpa/db/elexisdb_create_initial.xml#L905

**Comment by MakeITBetterSAGL** [comment]
Thanks again for your answer.
I did a 3.9 upgrade because in the wiki I found:

Voraussetzungen
    Vorgängerversion Elexis 3.7 oder 3.8 muss installiert sein.
    
I will now go thru 3.8 and see what happens. I added the allow_external but now I get an error that column TOTP is missing. 
Will try that as well. 

Thanks for your time and help. 
Have a nice day. :-)
Remo
