### ISSUE TITLE
Kann Elexis Core nicht starten

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#682]
Ich versuche, elexis-3-core in Eclipse zu starten. Dazu habe ich folgendes gemacht:

* Eine neue VirtualBox VM mit Ubuntu 24.4 erstellt
* Java 17 (openjdk-17-jdk) und Maven installiert
* https://github.com/elexis/elexis-3-core geklont
* Eclipse 2024-06 for RCP and RAP installiert und gestartet
* Java 17 als runtime jre eingestellt
* import ->import from git ->elexis-3-core
* ch.elexis.target/ide.target als target platform ausgewählt. Kompilieren lassen -> klappt
* Eine minimale Run-Konfiguration erstellt (Plugins->Features selected below -> Deselect all -> 
"ch.elexis.core.application feature" und "ch.elexis.core.common.feature" ausgewählt -> Select required -> Run

Der Start gelingt zunächst, und ich muss eine Datenbank-Verbindung angeben. Beim nächsten Start nach Konfiguration dieser Verbindung (mit einer existierenden und funktionierenden Datenbank) erhalte ich dann folgendes Log:

```
!SESSION 2024-07-07 08:21:36.865 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.11
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product ch.elexis.core.product.product
Command-line arguments:  -product ch.elexis.core.product.product -data /home/user/eclipse-workspace/../runtime-Minimal -dev file:/home/user/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/Minimal/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.eclipse.osgi 4 0 2024-07-07 08:21:44.503
!MESSAGE Application error
!STACK 1
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at ch.elexis.core.application.Desk.initIdentifiers(Desk.java:151)
	at ch.elexis.core.application.Desk.start(Desk.java:106)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

!ENTRY ch.elexis.core.data 4 0 2024-07-07 08:21:44.540
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in ch.elexis.core.data.activator.CoreHub.stop() of bundle ch.elexis.core.data.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:895)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "ch.elexis.core.services.ILocalLockService.releaseAllLocks()" because the return value of "ch.elexis.core.data.service.LocalLockServiceHolder.get()" is null
	at ch.elexis.core.data.activator.CoreHub.stop(CoreHub.java:270)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	... 13 more
Root exception:
java.lang.NullPointerException: Cannot invoke "ch.elexis.core.services.ILocalLockService.releaseAllLocks()" because the return value of "ch.elexis.core.data.service.LocalLockServiceHolder.get()" is null
	at ch.elexis.core.data.activator.CoreHub.stop(CoreHub.java:270)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
Da eine Menge "Magie" hinter den Kulissen passiert. hilft mir der Debugger auch nicht wirklich weiter. Offenbar fehlt irgend etwas bei `Desk.java.initIdentifiers()`

Versuchsweise in der Run-Konfiguration alle Features aktivieren ("All workspace and enabled target plugins") ändert allerdings auch nichts.

Irgendwelche ideen?

**Comment by huthomas** [comment]
Das sieht so aus als ob die `IAccessControlService` impl. nicht gestartet wird. Könnte mir vorstellen das es an der `@Reference` auf den `IContextService` liegt, da es da einee Test impl. gibt mit der ich auch schon Probleme hatte.

Generell sollte aber das `Elexis.product` aus `ch.elexis.core.p2site` verwendet werden um mit _Launch an Eclipse Application_ eine funktionierende run config zu erhalten.

**Comment by rgwch** [comment]
Vielen Dank, so hat der Start geklappt

**Comment by rgwch** [comment]
Kleiner Nachtrag: Die Verbindung scheitert zunächst, weil die Tabelle ch_elexis_omnivore_data fehlt. Das solltre nicht passieren, weil Omnivore ja ein optionales Plugin ist. Aber danach liess sich elexis 3.13 problemlos mit meiner Ungrad 2023-Datenbank verbinden.
