### ISSUE TITLE
No product built with Maven

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#684]
I'm trying to build elexis-3-core following these instructions: 
https://github.com/elexis/elexis-3-core/blob/master/ch.elexis.sdk/readme.md

(Only using java17, same setup as described here: https://github.com/elexis/elexis-3-core/issues/682)

`mvn -V clean verify  -Dtycho.localArtifacts=ignore -DskipTests`

Creates a lot of artifacts and ends with "BUILD SUCCESS" , but there is no `ch.elexis.core.p2site/target/products`.

What am I missing?

**Comment by huthomas** [comment]
The `-Dmaterialize-products` parameter is missing.

That info is now also included on the readme.md.

**Comment by rgwch** [comment]
Thanks a lot! 
Now it builds perfectly, but I'm still not lucky: Launch ends with

```
!SESSION 2024-07-14 07:33:40.589 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_CH
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2024-07-14 07:33:49.427
!MESSAGE Application error
!STACK 1
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at ch.elexis.core.application.Desk.initIdentifiers(Desk.java:151)
	at ch.elexis.core.application.Desk.start(Desk.java:106)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

!ENTRY ch.elexis.core.data 4 0 2024-07-14 07:33:49.539
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in ch.elexis.core.data.activator.CoreHub.stop() of bundle ch.elexis.core.data.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:895)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "ch.elexis.core.services.ILocalLockService.releaseAllLocks()" because the return value of "ch.elexis.core.data.service.LocalLockServiceHolder.get()" is null
	at ch.elexis.core.data.activator.CoreHub.stop(CoreHub.java:270)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	... 13 more
Root exception:
java.lang.NullPointerException: Cannot invoke "ch.elexis.core.services.ILocalLockService.releaseAllLocks()" because the return value of "ch.elexis.core.data.service.LocalLockServiceHolder.get()" is null
	at ch.elexis.core.data.activator.CoreHub.stop(CoreHub.java:270)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
(Tested with 3.12 and master branches).
Something is still missing in my setup...

**Comment by huthomas** [comment]
I can not reproduce this problem. Probably something went wrong connecting to the database.

Are there any errors at the start of the log?

**Comment by rgwch** [comment]
Thanks for looking into this!

This was all of workspace/.metadata/.log I got.
The logged error seems to me quite similar to that I encountered here: https://github.com/elexis/elexis-3-core/issues/682, But there I could solve it by using the Elexis.product from ch.elexis.core.p2site, as you suggested, which seems to contain the necessary magic (which I am not able to identify).
So, currently on the same machine at the same time, the Eclipse-IDE-based Elexis launches normally and connects to the database, while the maven-based version crashes.

The /home/user/elexis/elexis.log is here:
```
14:11:26.578 [Start Level: Equinox Container: 4451d08f-aee4-4595-874a-0253e405e46f] INFO  c.e.core.services.LocalConfigService - LocalConfig persisted to [/home/gerry/elexis/localCfg_default.xml]
14:11:26.581 [Start Level: Equinox Container: 4451d08f-aee4-4595-874a-0253e405e46f] INFO  c.elexis.core.data.activator.CoreHub - Basepath: bundleentry://11.fwk777386952/
14:11:28.032 [main] INFO  c.e.c.u.s.internal.ContextService - ACTIVATE
14:11:28.061 [main] INFO  ch.elexis.core.utils.OsgiServiceUtil - Release not active service [ch.elexis.core.jpa.datasource.internal.ElexisDataSourceService@7ea899a9] from 0 active references
14:11:33.067 [main] WARN  ch.elexis.core.utils.OsgiServiceUtil - ERR getServiceWait [ch.elexis.core.services.IAccessControlService]: 
14:11:33.068 [main] INFO  ch.elexis.core.utils.OsgiServiceUtil - Release not active service [org.apache.felix.scr.impl.runtime.ServiceComponentRuntimeImpl@2e1ddc90] from 0 active references
14:11:33.077 [main] ERROR PLATFORM - [org.eclipse.core.runtime] Application error
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at ch.elexis.core.application.Desk.initIdentifiers(Desk.java:151)
	at ch.elexis.core.application.Desk.start(Desk.java:106)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
14:11:33.121 [Framework stop - Equinox Container: 4451d08f-aee4-4595-874a-0253e405e46f] INFO  c.e.c.u.s.internal.ContextService - DEACTIVATE
14:11:33.129 [Framework stop - Equinox Container: 4451d08f-aee4-4595-874a-0253e405e46f] INFO  c.e.c.u.s.internal.ContextService - ACTIVATE
14:11:33.135 [Framework stop - Equinox Container: 4451d08f-aee4-4595-874a-0253e405e46f] INFO  c.e.c.u.s.internal.ContextService - DEACTIVATE
```

**Comment by rgwch** [comment]
Funny enough, it failed several times, also after deleting and re-cloning the repository. But: On a different machine (but also Linux and java 17) it works. So its ok for me now (but still mysterious).

**Comment by col-panic** [comment]
@rgwch please close this issue if resolved for you!

**Comment by rgwch** [comment]
It has always a bit of a "bad smell" for me, if it works or fails inconstantly, and I don't know why.
But, yes, in my current factory machines, it works.
